name: Generate Contributors PNG

on:
  push:
    paths:
      - '.all-contributorsrc'

jobs:
  build:
    if: github.ref == 'refs/heads/main' && github.repository == 'processing/p5.js'
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - name: Generate contributors image
        uses: skyash-dev/all-contributors-image@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
